var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.evalWorksForGlobals_=null;goog.provide=function(a){if(!COMPILED){if(goog.getObjectByName(a)&&!goog.implicitNamespaces_[a])throw Error('Namespace "'+a+'" already declared.');for(var b=a;b=b.substring(0,b.lastIndexOf("."));)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
COMPILED||(goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(d[e])d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var e=goog.dependencies_,g=0;d=b[g];g++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};
goog.require=function(a){if(!COMPILED&&!goog.getObjectByName(a)){var b=goog.getPathFromDeps_(a);if(b)goog.included_[b]=!0,goog.writeScripts_();else throw a="goog.require could not find: "+a,goog.global.console&&goog.global.console.error(a),Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){return a.instance_||(a.instance_=new a)}};
COMPILED||(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.inHtmlDocument_()){var a=goog.global.document;if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else for(var a=a.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.length;if("base.js"==c.substr(d-7)){goog.basePath=
c.substr(0,d-7);break}}}},goog.writeScriptTag_=function(a){goog.inHtmlDocument_()&&!goog.dependencies_.written[a]&&(goog.dependencies_.written[a]=!0,goog.global.document.write('<script type="text/javascript" src="'+a+'">\x3c/script>'))},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(f in d.nameToPath)a(d.nameToPath[f]);else if(!goog.getObjectByName(f))throw Error("Undefined nameToPath for "+f);
e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.writeScriptTag_(goog.basePath+b[e]);else throw Error("Undefined script input");},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.writeScriptTag_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array||!(a instanceof Object)&&"[object Array]"==Object.prototype.toString.call(a)||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&("[object Function]"==Object.prototype.toString.call(a)||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.propertyIsEnumerableCustom_=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return!0;return!1};goog.propertyIsEnumerable_=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):goog.propertyIsEnumerableCustom_(a,b)};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};
goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};
goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){a=goog.typeOf(a);return"object"==a||"array"==a||"function"==a};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);goog.uidCounter_=0;
goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};
goog.bind=function(a,b,c){var d=b||goog.global;if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,e);return a.apply(d,b)}}return function(){return a.apply(d,arguments)}};goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};
goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.typedef=!0;goog.getCssName=function(a,b){var c=a+(b?"-"+b:"");return goog.cssNameMapping_&&c in goog.cssNameMapping_?goog.cssNameMapping_[c]:c};goog.setCssNameMapping=function(a){goog.cssNameMapping_=a};goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};
goog.exportProperty=function(a,b,c){a[b]=c};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===d)g=!0;else if(g)return f.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};var wz={dmwa:{}};wz.dmwa.lib={};wz.dmwa.lib.templates={};wz.dmwa.lib.templates.index={compiledTemplates:{}};wz.dmwa.app={};wz.dmwa.app.templates={};wz.dmwa.app.templates.index={};
wz.dmwa.lib.templates.index.compiledTemplates.dishdetail_body_element=function(a){var b=[];b.push('<div id="dd-body-container">\n\n\t<div class="col-md-10 panel-info dd-panel-group ">\n\t\t<ul class="list-group panel-body">\n\t\t\t');_.each(a.dishDetail.getReviews(),function(a){b.push('\n\t\t\t\t<li class="list-group-item">\n\t\t\t\t\t<span class="glyphicon glyphicon-comment"></span>\n\t\t\t\t\t<span>',a,"</span>\n\t\t\t\t</li>\n\t\t\t")});b.push("\n\t\t</ul>\n\t</div>\n\n</div>\n");return b.join("")};
wz.dmwa.lib.templates.index.compiledTemplates.dishdetail_footer_element=function(a){var b=[];b.push('<nav class="col-md-10 navbar-fixed-bottom panel-info dd-panel-group">\n    <div class="panel-heading">\n        <h3 class="panel-title">',a.dishDetail.getRestaurantName(),'</h3>\n    </div>\n\n    <div class="panel-body dd-footer-info">\n        \n        \n        \x3c!--IOS--\x3e\n            <a href="maps:q=',a.dishDetail.getRestaurantAddr(),'">\n                ',a.dishDetail.getRestaurantAddr(),
'\n            </a>\n        \x3c!--END_IOS--\x3e\n\n        \x3c!-- NOT USED yet: launch google map app on ios\n        <a href="comgooglemaps://?q=',a.dishDetail.getRestaurantAddr(),'">\n            ',a.dishDetail.getRestaurantAddr(),"\n        </a>\n        --\x3e        \n        <p>",a.dishDetail.getRestaurantTel(),"</p>\n    </div>\n</nav>\n");return b.join("")};
wz.dmwa.lib.templates.index.compiledTemplates.dishdetail_header_element=function(a){var b=[];b.push('<div class="row navbar-fixed-top bg-primary">\n    <div id="dd-header-container">\n        <div class="col-xs-2 dd-header-bk-button">\n            <span class="glyphicon glyphicon-arrow-left success"/>\n        </div>\n\n        <div class="col-xs-7 dd-header-element dd-header-title">\n            <span>',a.dishDetail.getDishName(),'</span>\n        </div>\n\n        <div class="col-xs-3 dd-header-fav-icon">\n            <span class="glyphicon glyphicon-thumbs-up"></span>\n            <span>',
a.dishDetail.getReviews().length,"</span>\n        </div>\n    </div>\n</div>\n");return b.join("")};wz.dmwa.lib.templates.index.compiledTemplates.dishdetail_template=function(a){var b=[];b.push('<div class="header">\n    ',a.header(),'\n</div>\n<div class="body">\n    ',a.body(),'\n</div>\n<div class="footer">\n    ',a.footer(),"\n</div>\n");return b.join("")};
wz.dmwa.lib.templates.index.compiledTemplates.dishlist_body_template=function(a){var b=[];b.push('<div id="dl-body-container">\n\t');_.each(a.dish_list,function(a){b.push('\n\t\t<div class="list-group-item col-md-12 dl-item-group">\n\t\t\t<h3 class="list-group-item-heading text-primary dl-item-title" dishid="',a.getDishId(),'">',a.getDishName(),'</h3>\n\t\t\t<p class="list-group-item-text dl-item-text"><span class="label label-info">',a.getRestaurantName(),'</span></p>\n\t\t\t<p class="list-group-item-text">',
a.getLikes(),' loved it <span class="glyphicon glyphicon-heart"></span> | ',a.getDistance()," mi</p>\n\t\t</div>\n\t")});b.push("\n</div>\n");return b.join("")};wz.dmwa.lib.templates.index.compiledTemplates.dishlist_footer_template=function(){var a=[];a.push('<div id="dl-footer-container" class="col-md-4">\n\x3c!-- \t<form role="search">\n\t\t<input type="text" class="form-control">\n\t\t<button type="submit" class="btn btn-success">Search</button>\n\t</form> --\x3e\n</div>\n');return a.join("")};
wz.dmwa.lib.templates.index.compiledTemplates.dishlist_header_template=function(){var a=[];a.push('<div id="dl-header-container" class="col-md-12 navbar-fixed-top bg-primary">\n\t<h3>Best Dishes Around You</h3>\n</div>');return a.join("")};wz.dmwa.lib.templates.index.compiledTemplates.dishlist_template=function(a){var b=[];b.push('<div class="header">\n    ',a.header(),'\n</div>\n<div class="body">\n    ',a.body(),'\n</div>\n<div class="footer">\n    ',a.footer(),"\n</div>\n");return b.join("")};wz.dmwa.lib.log={};(function(){wz.dmwa.lib.log=function(){var a=new Date,b=["wz.dmwa | "+(a.getHours()+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds())+" |"];_.each(arguments,function(a){b.push(a)});window.console.log.apply(console,b)}})();wz.dmwa.lib.Object={};(function(){wz.dmwa.lib.Object=function(){this.initialize.apply(this,arguments)};_.extend(wz.dmwa.lib.Object.prototype,{_logNamespace:"Object",initialize:function(){},_log:function(a){wz.dmwa.lib.log(this._logNamespace+": "+a)}});wz.dmwa.lib.Object.extend=Backbone.Model.extend})();wz.dmwa.core={};wz.dmwa.core.controllers={};wz.dmwa.core.controllers.Controller={};
(function(){wz.dmwa.core.controllers.Controller=wz.dmwa.lib.Object.extend({_businessEvents:{},_logNamespace:"Controller",initialize:function(){this._asyncServices=[];this._log("Controller Initizlized")},start:function(){this._initializeModels();this._view||(this._view=this._getView());this._initializeBusinessEvents();this._bindViewEvents(this._view,this._businessEvents)},startAsync:function(a){var b=this._loadAsyncServices(),c=_.bind(function(){this.start(a)},this);b.done(c);return b},_loadAsyncServices:function(){var a=
_.map(this._asyncServices,function(a){return a.load()});return $.when.apply(null,a)},stop:function(){this._view&&(this._view.unbind(),this._view.stop());this._asyncServices&&(this._asyncServices=[])},_initializeModels:function(){this._log("Controller: _initializeModels")},_initializeBusinessEvents:function(){this._log("Controller: _initializeBusinessEvents")},_bindViewEvents:function(a,b){_.each(b,$.proxy(function(b,d){a.bind(d,$.proxy(b,this))},this));this._log("Controller: _bindViewEvents")},_unbindViewEvents:function(a,
b){_.each(b,$.proxy(function(b,d){a.unbind(d)},this));this._log("Controller: _unbindViewEvents")}})})();goog.debug={};goog.debug.Error=function(a){this.stack=Error().stack||"";a&&(this.message=String(a))};goog.inherits(goog.debug.Error,Error);goog.debug.Error.prototype.name="CustomError";goog.string={};goog.string.Unicode={NBSP:"\u00a0"};goog.string.startsWith=function(a,b){return 0==a.lastIndexOf(b,0)};goog.string.endsWith=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};goog.string.caseInsensitiveStartsWith=function(a,b){return 0==goog.string.caseInsensitiveCompare(b,a.substr(0,b.length))};goog.string.caseInsensitiveEndsWith=function(a,b){return 0==goog.string.caseInsensitiveCompare(b,a.substr(a.length-b.length,b.length))};
goog.string.subs=function(a,b){for(var c=1;c<arguments.length;c++){var d=String(arguments[c]).replace(/\$/g,"$$$$");a=a.replace(/\%s/,d)}return a};goog.string.collapseWhitespace=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};goog.string.isEmpty=function(a){return/^[\s\xa0]*$/.test(a)};goog.string.isEmptySafe=function(a){return goog.string.isEmpty(goog.string.makeSafe(a))};goog.string.isBreakingWhitespace=function(a){return!/[^\t\n\r ]/.test(a)};goog.string.isAlpha=function(a){return!/[^a-zA-Z]/.test(a)};
goog.string.isNumeric=function(a){return!/[^0-9]/.test(a)};goog.string.isAlphaNumeric=function(a){return!/[^a-zA-Z0-9]/.test(a)};goog.string.isSpace=function(a){return" "==a};goog.string.isUnicodeChar=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};goog.string.stripNewlines=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};goog.string.canonicalizeNewlines=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
goog.string.normalizeWhitespace=function(a){return a.replace(/\xa0|\s/g," ")};goog.string.normalizeSpaces=function(a){return a.replace(/\xa0|[ \t]+/g," ")};goog.string.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};goog.string.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};goog.string.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};goog.string.caseInsensitiveCompare=function(a,b){var c=String(a).toLowerCase(),d=String(b).toLowerCase();return c<d?-1:c==d?0:1};
goog.string.numerateCompareRegExp_=/(\.\d+)|(\d+)|(\D+)/g;goog.string.numerateCompare=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(goog.string.numerateCompareRegExp_),d=b.toLowerCase().match(goog.string.numerateCompareRegExp_),e=Math.min(c.length,d.length),g=0;g<e;g++){var f=c[g],j=d[g];if(f!=j)return c=parseInt(f,10),!isNaN(c)&&(d=parseInt(j,10),!isNaN(d)&&c-d)?c-d:f<j?-1:1}return c.length!=d.length?c.length-d.length:a<b?-1:1};
goog.string.encodeUriRegExp_=/^[a-zA-Z0-9\-_.!~*'()]*$/;goog.string.urlEncode=function(a){a=String(a);return!goog.string.encodeUriRegExp_.test(a)?encodeURIComponent(a):a};goog.string.urlDecode=function(a){return decodeURIComponent(a.replace(/\+/g," "))};goog.string.newLineToBr=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};
goog.string.htmlEscape=function(a,b){if(b)return a.replace(goog.string.amperRe_,"&amp;").replace(goog.string.ltRe_,"&lt;").replace(goog.string.gtRe_,"&gt;").replace(goog.string.quotRe_,"&quot;");if(!goog.string.allRe_.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(goog.string.amperRe_,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(goog.string.ltRe_,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(goog.string.gtRe_,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(goog.string.quotRe_,"&quot;"));return a};
goog.string.amperRe_=/&/g;goog.string.ltRe_=/</g;goog.string.gtRe_=/>/g;goog.string.quotRe_=/\"/g;goog.string.allRe_=/[&<>\"]/;goog.string.unescapeEntities=function(a){return goog.string.contains(a,"&")?"document"in goog.global&&!goog.string.contains(a,"<")?goog.string.unescapeEntitiesUsingDom_(a):goog.string.unescapePureXmlEntities_(a):a};
goog.string.unescapeEntitiesUsingDom_=function(a){var b=goog.global.document.createElement("div");b.innerHTML="<pre>x"+a+"</pre>";if(b.firstChild[goog.string.NORMALIZE_FN_])b.firstChild[goog.string.NORMALIZE_FN_]();a=b.firstChild.firstChild.nodeValue.slice(1);b.innerHTML="";return goog.string.canonicalizeNewlines(a)};
goog.string.unescapePureXmlEntities_=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})};goog.string.NORMALIZE_FN_="normalize";goog.string.whitespaceEscape=function(a,b){return goog.string.newLineToBr(a.replace(/  /g," &#160;"),b)};
goog.string.stripQuotes=function(a,b){for(var c=b.length,d=0;d<c;d++){var e=1==c?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};goog.string.truncate=function(a,b,c){c&&(a=goog.string.unescapeEntities(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=goog.string.htmlEscape(a));return a};
goog.string.truncateMiddle=function(a,b,c,d){c&&(a=goog.string.unescapeEntities(a));if(d){d>b&&(d=b);var e=a.length-d;a=a.substring(0,b-d)+"..."+a.substring(e)}else a.length>b&&(d=Math.floor(b/2),e=a.length-d,a=a.substring(0,d+b%2)+"..."+a.substring(e));c&&(a=goog.string.htmlEscape(a));return a};goog.string.specialEscapeChars_={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};goog.string.jsEscapeCache_={"'":"\\'"};
goog.string.quote=function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0);b[c+1]=goog.string.specialEscapeChars_[d]||(31<e&&127>e?d:goog.string.escapeChar(d))}b.push('"');return b.join("")};goog.string.escapeString=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=goog.string.escapeChar(a.charAt(c));return b.join("")};
goog.string.escapeChar=function(a){if(a in goog.string.jsEscapeCache_)return goog.string.jsEscapeCache_[a];if(a in goog.string.specialEscapeChars_)return goog.string.jsEscapeCache_[a]=goog.string.specialEscapeChars_[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return goog.string.jsEscapeCache_[a]=b};goog.string.toMap=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=!0;return b};
goog.string.contains=function(a,b){return-1!=a.indexOf(b)};goog.string.removeAt=function(a,b,c){var d=a;0<=b&&(b<a.length&&0<c)&&(d=a.substr(0,b)+a.substr(b+c,a.length-b-c));return d};goog.string.remove=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"");return a.replace(c,"")};goog.string.removeAll=function(a,b){var c=RegExp(goog.string.regExpEscape(b),"g");return a.replace(c,"")};
goog.string.regExpEscape=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};goog.string.repeat=function(a,b){return Array(b+1).join(a)};goog.string.padNumber=function(a,b,c){a=goog.isDef(c)?a.toFixed(c):String(a);c=a.indexOf(".");-1==c&&(c=a.length);return goog.string.repeat("0",Math.max(0,b-c))+a};goog.string.makeSafe=function(a){return null==a?"":String(a)};goog.string.buildString=function(a){return Array.prototype.join.call(arguments,"")};
goog.string.getRandomString=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^goog.now()).toString(36)};
goog.string.compareVersions=function(a,b){for(var c=0,d=goog.string.trim(String(a)).split("."),e=goog.string.trim(String(b)).split("."),g=Math.max(d.length,e.length),f=0;0==c&&f<g;f++){var j=d[f]||"",l=e[f]||"",m=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var k=m.exec(j)||["","",""],h=n.exec(l)||["","",""];if(0==k[0].length&&0==h[0].length)break;var c=0==k[1].length?0:parseInt(k[1],10),p=0==h[1].length?0:parseInt(h[1],10),c=goog.string.compareElements_(c,p)||goog.string.compareElements_(0==
k[2].length,0==h[2].length)||goog.string.compareElements_(k[2],h[2])}while(0==c)}return c};goog.string.compareElements_=function(a,b){return a<b?-1:a>b?1:0};goog.string.HASHCODE_MAX_=4294967296;goog.string.hashCode=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=goog.string.HASHCODE_MAX_;return b};goog.string.uniqueStringCounter_=2147483648*Math.random()|0;goog.string.createUniqueString=function(){return"goog_"+goog.string.uniqueStringCounter_++};
goog.string.toNumber=function(a){var b=Number(a);return 0==b&&goog.string.isEmpty(a)?NaN:b};goog.string.toCamelCaseCache_={};goog.string.toCamelCase=function(a){return goog.string.toCamelCaseCache_[a]||(goog.string.toCamelCaseCache_[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};goog.string.toSelectorCaseCache_={};goog.string.toSelectorCase=function(a){return goog.string.toSelectorCaseCache_[a]||(goog.string.toSelectorCaseCache_[a]=String(a).replace(/([A-Z])/g,"-$1").toLowerCase())};goog.asserts={};goog.asserts.ENABLE_ASSERTS=goog.DEBUG;goog.asserts.AssertionError=function(a,b){b.unshift(a);goog.debug.Error.call(this,goog.string.subs.apply(null,b));b.shift();this.messagePattern=a};goog.inherits(goog.asserts.AssertionError,goog.debug.Error);goog.asserts.AssertionError.prototype.name="AssertionError";goog.asserts.doAssertFailure_=function(a,b,c,d){var e="Assertion failed";if(c)var e=e+(": "+c),g=d;else a&&(e+=": "+a,g=b);throw new goog.asserts.AssertionError(""+e,g||[]);};
goog.asserts.assert=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!a&&goog.asserts.doAssertFailure_("",null,b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.fail=function(a,b){if(goog.asserts.ENABLE_ASSERTS)throw new goog.asserts.AssertionError("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};
goog.asserts.assertNumber=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isNumber(a)&&goog.asserts.doAssertFailure_("Expected number but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertString=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isString(a)&&goog.asserts.doAssertFailure_("Expected string but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertFunction=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isFunction(a)&&goog.asserts.doAssertFailure_("Expected function but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertObject=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isObject(a)&&goog.asserts.doAssertFailure_("Expected object but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertArray=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isArray(a)&&goog.asserts.doAssertFailure_("Expected array but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};goog.asserts.assertBoolean=function(a,b,c){goog.asserts.ENABLE_ASSERTS&&!goog.isBoolean(a)&&goog.asserts.doAssertFailure_("Expected boolean but got %s: %s.",[goog.typeOf(a),a],b,Array.prototype.slice.call(arguments,2));return a};
goog.asserts.assertInstanceof=function(a,b,c,d){goog.asserts.ENABLE_ASSERTS&&!(a instanceof b)&&goog.asserts.doAssertFailure_("instanceof check failed.",null,c,Array.prototype.slice.call(arguments,3))};wz.dmwa.lib.templates.renderTemplate={};(function(){var a=wz.dmwa.lib.templates.index.compiledTemplates,b=goog.asserts;wz.dmwa.lib.templates.renderTemplate=function(c,d){d=d||{};var e=a[c];b.assert(e,c+" not compiled");return e(d)}})();wz.dmwa.core.templates={};wz.dmwa.core.templates.Template={};
(function(){wz.dmwa.core.templates.Template=function(a){this.initialize(a)};_.extend(wz.dmwa.core.templates.Template.prototype,{initialize:function(){this._logNamespace="Template"},_getTemplate:function(a){goog.asserts.assert(this.templateId,"templateId must be defined in Template subclass");a=a||{};return wz.dmwa.lib.templates.renderTemplate(this.templateId,a)},render:function(){return this._getTemplate(this)},_log:function(a){wz.dmwa.lib.log(this._logNamespace+": "+a)}});wz.dmwa.core.templates.Template.extend=
Backbone.Model.extend})();wz.dmwa.app.templates.DishlistTemplate={};
(function(){var a=wz.dmwa.core.templates.Template,b=wz.dmwa.lib.templates.renderTemplate;wz.dmwa.app.templates.DishlistTemplate=a.extend({templateId:"dishlist_template",initialize:function(b){a.prototype.initialize.call(this,b);this._logNamespace="dishlist_template";this.dish_list=b.dish_list},header:function(){return b("dishlist_header_template",this)},body:function(){return b("dishlist_body_template",this)},footer:function(){return b("dishlist_footer_template",this)}})})();wz.dmwa.core.views={};wz.dmwa.core.views.View={};
(function(){var a=/^(\w+)\s*(.*)$/;wz.dmwa.core.views.View=Backbone.View.extend({el:$("#home"),EVENTS:{},toBeUndelegated:[],_domEvents:{},downstateDelegateExceptions:[],_logNamespace:"View",initialize:function(a){a=a||{};a.cssClass&&this.$el.attr("class",a.cssClass)},start:function(){this.delegateEvents(this._domEvents)},stop:function(){this.$el.empty();this.$el.unbind()},delegateEvents:function(b){this.toBeUndelegated=[];for(var c in b){var d=c.match(a)[2],e=$("body");""!==d&&(!_.contains(this.toBeUndelegated,
d)&&!_.contains(this.downstateDelegateExceptions,d))&&(e.delegate(d,"vmousedown",this._addDownstate),e.delegate(d,"vmouseup",this._removeDownstate),e.delegate(d+".down","mouseout",this._removeDownstate),this.toBeUndelegated.push(d))}this._delegateEvents(b)},_delegateEvents:function(b){if(b=b||this.events){var c=this.$el;c.unbind();for(var d in b){var e=b[d],e=_.bind(e,this),g=d.match(a),f=g[1],g=g[2];""===g?c.bind(f,e):c.delegate(g,f,e)}}},_addDownstate:function(a){$(a.currentTarget).addClass("down")},
_removeDownstate:function(a){$(a.currentTarget).removeClass("down")}})})();wz.dmwa.app.views={};wz.dmwa.app.views.DishlistView={};
(function(){var a=wz.dmwa.core.views.View,b=wz.dmwa.app.templates.DishlistTemplate;wz.dmwa.app.views.DishlistView=a.extend({EVENTS:{GO_TO_DETAIL:"go_to_detail"},_logNamespace:"DishlistView",initialize:function(b){this._domEvents=_.extend({},this._domEvents,{"click .dl-item-group":this._clickDishTitleHandler});a.prototype.initialize.call(this,b);this._logNamespace="DishlistView";this._spinner=this._get_spinner()},_get_spinner:function(){return new Spinner({lines:13,length:20,width:10,radius:30,trail:60,
className:"spinner",top:"50%",left:"50%"})},_createTemplate:function(a){return new b(a)},startLoadingSpinner:function(){var a=document.getElementById("home");$(a).append("<h3>Finding best dishes around you ...</h3>");this._spinner.spin(a)},stopLoadingSpinner:function(){this._spinner.stop()},start:function(b){this._render(b);a.prototype.start.call(this)},_render:function(a){a=this._createTemplate(a).render();this.$el.empty().append(a)},showZeroState:function(){alert("Sorry, no dishes found round you")},
_clickDishTitleHandler:function(a){a=a.currentTarget;$(a).addClass("dl-highlight");a=a.getElementsByClassName("dl-item-title")[0].getAttribute("dishid");this.trigger(this.EVENTS.GO_TO_DETAIL,a)},getCurrentScrollPosition:function(){return $(window).scrollTop()},goToScrollPosition:function(a){$(window).scrollTop(a)}})})();wz.dmwa.core.models={};wz.dmwa.core.models.Model={};
(function(){wz.dmwa.core.models.Model=Backbone.Model.extend({STATES:{NEW_:0,MODIFIED:1,CLEAN:2,DELETED:3},FIELDS:{ID:"id",STATE:"state",CLIENT_CREATE_DATE:"ccdate",CLIENT_MOD_DATE:"cmddate"},initialize:function(a){var b=this.FIELDS,c=this.STATES;this.cid=Math.floor(1E6*Math.random()+1);var d={};a?(this.id=a[b.ID]||this.cid,b.STATE in a||(d[b.STATE]=a[b.ID]?c.CLEAN:c.NEW_)):(this.id=this.cid,d[b.STATE]=c.NEW_);d[b.ID]=this.id;this.set(d,{silent:!0});this._updateTimestamps();this.bind("change",$.proxy(this._onChange,
this));this._logNamespace="Model"},getId:function(){return this.get(this.FIELDS.ID)},getState:function(){return this.get(this.FIELDS.STATE)},setStateClean:function(){var a={};a[this.FIELDS.STATE]=this.STATES.CLEAN;this.set(a,{silent:!0})},setStateDeleted:function(){var a={};a[this.FIELDS.STATE]=this.STATES.DELETED;this.set(a,{silent:!0})},getClientCreateDate:function(){return this.get(this.FIELDS.CLIENT_CREATE_DATE)},getClientModDate:function(){return this.get(this.FIELDS.CLIENT_MOD_DATE)},isNew:function(){return this.getState()===
this.STATES.NEW_},isClean:function(){return this.getState()===this.STATES.CLEAN},isModified:function(){return this.getState()===this.STATES.MODIFIED},isDirty:function(){return this.getState()!==this.STATES.CLEAN},_onChange:function(){var a=this.STATES;this.getState()===a.CLEAN&&this.set(this.FIELDS.STATE,a.MODIFIED,{silent:!0});this._updateTimestamps()},_updateTimestamps:function(){var a=(new Date).toISOString(),b={};b[this.FIELDS.CLIENT_MOD_DATE]=a;this.get(this.FIELDS.CLIENT_CREATE_DATE)||(b[this.FIELDS.CLIENT_CREATE_DATE]=
a);this.set(b,{silent:!0})},_log:function(a){wz.dmwa.lib.log(this._logNamespace+": "+a)}})})();wz.dmwa.app.models={};wz.dmwa.app.models.DishlistItem={};
(function(){var a=wz.dmwa.core.models.Model;wz.dmwa.app.models.DishlistItem=a.extend({FIELDS:_.extend({},a.prototype.FIELDS,{ID:"id",FOOT_TEXT:"foodText",BIZ_NAME:"bizName",FREQ:"freq",DISTANCE:"distance"}),initialize:function(b){a.prototype.initialize.call(this,b);b=_.extend({},b);this.set(b);this._logNamespace="DishlistItem"},getDishId:function(){return this.get(this.FIELDS.ID)},getDishName:function(){return this.get(this.FIELDS.FOOT_TEXT)},getRestaurantName:function(){return this.get(this.FIELDS.BIZ_NAME)},
getLikes:function(){return this.get(this.FIELDS.FREQ)},getDistance:function(){return this.get(this.FIELDS.DISTANCE)}})})();wz.dmwa.app.collections={};wz.dmwa.app.collections.DishlistItemCollection={};(function(){var a=wz.dmwa.app.models.DishlistItem,b=a.prototype.FIELDS;wz.dmwa.app.collections.DishlistItemCollection=Backbone.Collection.extend({_logNamespace:"DishlistItemCollection",model:a,localStorage:new Backbone.LocalStorage("DishlistItemCollection"),comparator:function(a){return-a.get(b.FREQ)}})})();wz.dmwa.core.services={};wz.dmwa.core.services.Service={};(function(){wz.dmwa.core.services.Service=wz.dmwa.lib.Object.extend({_logNamespace:"Service",_asyncServices:[],load:function(){if(_.isEmpty(this._asyncServices))return $.Deferred().resolve().promise();var a=_.map(this._asyncServices,function(a){return a.load()});return $.when.apply(null,a)}})})();wz.dmwa.app.services={};wz.dmwa.app.services.LocationService={};
(function(){var a=wz.dmwa.core.services.Service,b=a.extend({_logNamespace:"LocationService",initialize:function(){a.prototype.initialize.call(this)},load:function(){var a=this;return this._queryCurrentLocation().done(function(b){a._pos=b})},get_lat:function(){return this._pos.coords.latitude},get_lon:function(){return this._pos.coords.longitude},_queryCurrentLocation:function(){var a=$.Deferred();this._pos?a.resolve(this._pos):navigator.geolocation.getCurrentPosition(function(b){a.resolve(b)},function(a){alert("code: "+
a.code+"\nmessage: "+a.message+"\n")},{enableHighAccuracy:!0,timeout:15E3,maximumAge:3E4});return a.promise()},getDistanceFromLatLonInMi:function(a,b){function e(a){return a*(Math.PI/180)}var g=e(a-this.get_lat()),f=e(b-this.get_lon()),g=Math.sin(g/2)*Math.sin(g/2)+Math.cos(e(this.get_lat()))*Math.cos(e(this.get_lon()))*Math.sin(f/2)*Math.sin(f/2);return(3959*2*Math.atan2(Math.sqrt(g),Math.sqrt(1-g))).toPrecision(1)}});wz.dmwa.app.services.LocationService=new b})();wz.dmwa.app.models.Dishdetail={};
(function(){var a=wz.dmwa.core.models.Model;wz.dmwa.app.models.Dishdetail=a.extend({FIELDS:_.extend({},a.prototype.FIELDS,{FOOD_ID:"id",FOOD_TEXT:"foodText",FREQ:"freq",REVIEWS:"reviews",BIZ_NAME:"bizName",BIZ_ADDR:"bizAddr",BIZ_TEL:"bizTel"}),initialize:function(b){b=_.extend({},b);a.prototype.initialize.call(this,b);this.set(b);this._logNamespace="Dishdetail"},getFoodId:function(){return this.get(this.FIELDS.FOOD_ID)},getReviews:function(){var a=this.get(this.FIELDS.REVIEWS);return _.map(a,function(a){return a.text})},
getDishName:function(){return this.get(this.FIELDS.FOOD_TEXT)},getRestaurantName:function(){return this.get(this.FIELDS.BIZ_NAME)},getLikes:function(){return this.get(this.FIELDS.FREQ)},getRestaurantAddr:function(){return this.get(this.FIELDS.BIZ_ADDR)},getRestaurantTel:function(){var a=this.get(this.FIELDS.BIZ_TEL);return"("+a.slice(0,3)+") "+a.slice(3,6)+"-"+a.slice(6,10)}})})();wz.dmwa.app.collections.DishdetailCollection={};(function(){wz.dmwa.app.collections.DishdetailCollection=Backbone.Collection.extend({_logNamespace:"DishdetailCollection",model:wz.dmwa.app.models.Dishdetail,localStorage:new Backbone.LocalStorage("DishdetailCollection")})})();wz.dmwa.app.services.APIService={};
(function(){var a=wz.dmwa.core.services.Service,b=wz.dmwa.app.services.LocationService,c=wz.dmwa.app.collections.DishlistItemCollection,d=wz.dmwa.app.collections.DishdetailCollection,e=wz.dmwa.app.models.Dishdetail,g=wz.dmwa.app.models.DishlistItem,f=a.extend({_logNamespace:"APIService",initialize:function(){a.prototype.initialize.call(this);this._is_first_load=!0},load:function(){var a=$.Deferred(),c=this;if(this._is_first_load){var d=b.load();d.done(function(){var d=b.get_lat(),e=b.get_lon();$.ajax({dataType:"json",
url:"http://192.241.173.181:8080/food/where/",data:{lat:d,lon:e,version:2},success:function(b){c._clear_local_storage();c._save_data(b);c._is_first_load=!1;a.resolve()}})});d.fail(function(){a.reject()});return a.promise()}a.resolve()},_mapRawToDishlistItem:function(a,c,d,e){var f={},h=g.prototype.FIELDS;f[h.ID]=a.id;f[h.FOOT_TEXT]=a.foodText;f[h.FREQ]=a.freq;a=b.getDistanceFromLatLonInMi(d,e);f[h.DISTANCE]=a;f[h.BIZ_NAME]=c;return new g(f)},_clear_local_storage:function(){window.localStorage.clear()},
_save_data:function(a){var b=a.dishes,e=a.businesses,f=this;a=_.map(b,function(a){var b=_.findWhere(e,{bizID:a.bizID});return f._mapRawToDishlistItem(a,b.name,b.lat,b.lon)});var g=new c;_.each(a,function(a){g.add(a);a.save()});var b=_.map(b,function(a){var b=_.findWhere(e,{bizID:a.bizID});return f._mapRawToDishdetail(a,b)}),h=new d;_.each(b,function(a){h.add(a);a.save()})},_mapRawToDishdetail:function(a,b){var c={},d=e.prototype.FIELDS;c[d.FOOD_ID]=a.id;c[d.FOOD_TEXT]=a.foodText;c[d.FREQ]=a.freq;
c[d.REVIEWS]=a.reviews;c[d.BIZ_NAME]=b.name;c[d.BIZ_ADDR]=b.address;c[d.BIZ_TEL]=b.phone;return new e(c)},getDishes:function(){return new Backbone.Collection(this._json.dishes)},getBusinesses:function(){return new Backbone.Collection(this._json.businesses)}});wz.dmwa.app.services.APIService=new f})();wz.dmwa.app.services.DishlistService={};
(function(){var a=wz.dmwa.core.services.Service,b=wz.dmwa.app.collections.DishlistItemCollection,c=a.extend({_logNamespace:"DishlistService",_apiService:wz.dmwa.app.services.APIService,initialize:function(){this._dishCollection=new b;this._asyncServices.push(this._apiService);a.prototype.initialize.call(this)},_initializeModels:function(){},allDishes:function(){var a=this._dishCollection.localStorage.findAll();this._dishCollection.reset(a);return this._dishCollection.models},saveScrollPosition:function(a){this._scrollPos=
a},hasScrollPosition:function(){return void 0!==this._scrollPos?!0:!1},getScrollPosition:function(){return this._scrollPos}});wz.dmwa.app.services.DishlistService=new c})();wz.dmwa.app.controllers={};wz.dmwa.app.controllers.DishlistController={};
(function(){var a=wz.dmwa.core.controllers.Controller,b=wz.dmwa.app.views.DishlistView,c=wz.dmwa.app.services.DishlistService;wz.dmwa.app.controllers.DishlistController=a.extend({_logNamespace:"DishlistController",initialize:function(b){a.prototype.initialize.call(this,b);this._service=c;this._asyncServices.push(this._service);this._view=this._getView();this._view.startLoadingSpinner()},start:function(){a.prototype.start.call(this);var b={};b.dish_list=this._service.allDishes();this._view.stopLoadingSpinner();
this._view.start(b);if(this._service.hasScrollPosition()){var c=this._service.getScrollPosition();this._view.goToScrollPosition(c)}0==_.size(b.dish_list)&&this._view.showZeroState()},_initializeModels:function(){this._log("TodoController: _initializeModels")},_initializeBusinessEvents:function(){this._log("DishlistController: _initializeBusinessEvents");this._businessEvents[b.prototype.EVENTS.GO_TO_DETAIL]=this._onGoTODetail;a.prototype._initializeBusinessEvents.call(this)},_onGoTODetail:function(a){this._service.saveScrollPosition(this._view.getCurrentScrollPosition());
window.location.href="#dishdetail/"+a},_getView:function(){return new b}})})();wz.dmwa.app.services.DishdetailService={};(function(){var a=wz.dmwa.core.services.Service,b=wz.dmwa.app.collections.DishdetailCollection,c=a.extend({_logNamespace:"DishdetailService",initialize:function(){a.prototype.initialize.call(this);this._collection=new b},getDishDetail:function(a){var b=this._collection.localStorage.findAll();this._collection.reset(b);return this._collection.get(a)}});wz.dmwa.app.services.DishdetailService=new c})();wz.dmwa.app.templates.DishdetailTemplate={};
(function(){var a=wz.dmwa.core.templates.Template,b=wz.dmwa.lib.templates.renderTemplate;wz.dmwa.app.templates.DishdetailTemplate=a.extend({templateId:"dishdetail_template",initialize:function(b){a.prototype.initialize.call(this,b);this._logNamespace="dishdetail_template";this.dishDetail=b.dishDetail},header:function(){return b("dishdetail_header_element",this)},body:function(){return b("dishdetail_body_element",this)},footer:function(){return b("dishdetail_footer_element",this)}})})();wz.dmwa.app.views.DishdetailView={};
(function(){var a=wz.dmwa.core.views.View,b=wz.dmwa.app.templates.DishdetailTemplate;wz.dmwa.app.views.DishdetailView=a.extend({EVENTS:{GO_BACK:"go_back"},_logNamespace:"DishlistView",initialize:function(b){this._domEvents=_.extend({},this._domEvents,{"click .dd-header-bk-button":this._backButtonClickHandler});a.prototype.initialize.call(this,b);this._logNamespace="DishlistView"},_backButtonClickHandler:function(){$(".dd-header-bk-button span").addClass("back-btn-orange");this.trigger(this.EVENTS.GO_BACK)},
_createTemplate:function(a){return new b(a)},start:function(b){this._render(b);a.prototype.start.call(this);$(window).scrollTop(0)},_render:function(a){a=this._createTemplate(a).render();this.$el.empty().append(a)}})})();wz.dmwa.app.controllers.DishdetailController={};
(function(){var a=wz.dmwa.core.controllers.Controller,b=wz.dmwa.app.views.DishdetailView,c=wz.dmwa.app.services.DishdetailService;wz.dmwa.app.controllers.DishdetailController=a.extend({_logNamespace:"DishdetailController",initialize:function(b){this._dishId=b;this._service=c;a.prototype.initialize.call(this,b)},start:function(){a.prototype.start.call(this);var b={};b.dishDetail=this._service.getDishDetail(this._dishId);this._view.start(b)},_initializeModels:function(){},_initializeBusinessEvents:function(){this._businessEvents[b.prototype.EVENTS.GO_BACK]=
this._onGoBack;a.prototype._initializeBusinessEvents.call(this)},_getView:function(){return new b},_onGoBack:function(){window.location.href="#dishlist"}})})();wz.dmwa.app.routers={};wz.dmwa.app.routers.AppRouter={};
(function(){var a=null,b=Backbone.Router.extend({_logNamespace:"AppRouter",routes:{dishlist:"runDishlistController","dishdetail/:dishId":"runDishdetailController"},runDishlistController:function(a){this._runController(wz.dmwa.app.controllers.DishlistController,a)},runDishdetailController:function(a){this._runController(wz.dmwa.app.controllers.DishdetailController,a)},_runController:function(b,d){var e=this;setTimeout(function(){e._tearDownCurrentController();a=new b(d);a.startAsync()},200)},_tearDownCurrentController:function(){a&&
a.stop()}});wz.dmwa.app.routers.AppRouter=new b;Backbone.history.start();wz.dmwa.app.routers.AppRouter.runDishlistController()})();wz.dmwa.require_file={};
